@baseUrl = http://localhost:5165


### Get all drivers
GET {{baseUrl}}/drivers HTTP/1.1


### Get a driver by Id
GET {{baseUrl}}/drivers/9 HTTP/1.1


### Post a driver
POST {{baseUrl}}/drivers HTTP/1.1
Content-Type: application/json

{
    "name": "Eugenio"
}

### Delete a driver
DELETE {{baseUrl}}/drivers/1 HTTP/1.1


### Delete all drivers
DELETE {{baseUrl}}/drivers HTTP/1.1
